/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSelector: typeof import('./components/AdvancedSelector.vue')['default']
    AdvancedTable: typeof import('./components/AdvancedTable.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    ButtonCell: typeof import('./components/table-cells/ButtonCell.vue')['default']
    EditableCell: typeof import('./components/table-cells/EditableCell.vue')['default']
    FeedbackPanel: typeof import('./components/FeedbackPanel.vue')['default']
    FullscreenButton: typeof import('./components/FullscreenButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ImageCell: typeof import('./components/table-cells/ImageCell.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    ModalWindow: typeof import('./components/ModalWindow.vue')['default']
    NoticeBar: typeof import('./components/NoticeBar.vue')['default']
    OperationLogPanel: typeof import('./components/OperationLogPanel.vue')['default']
    RightSideModal: typeof import('./components/RightSideModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusCell: typeof import('./components/table-cells/StatusCell.vue')['default']
    SubProjectAddCell: typeof import('./components/table-cells/SubProjectAddCell.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TextCell: typeof import('./components/table-cells/TextCell.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    TreeNodeItem: typeof import('./components/TreeNodeItem.vue')['default']
  }
}
